// Generated by Wrangler on Wed Jul 10 2024 13:43:22 GMT+0100 (British Summer Time)
// by running `wrangler types`

interface Env {
	__CACHE: KVNamespace;
	SESSION_SECRET: string;
	CONTENT_GITHUB_TOKEN: string;
}
